#!/usr/bin/env bash
#
# Starts the whole backend under pm2, pointed at Cloud SQL and Memorystore.
#
#   ./vm-start.sh                    # settings from vm.env
#   ./vm-start.sh --seed             # first run on an empty database
#   ./vm-start.sh --db-host 10.1.2.3 --db-password 'hunter2'
#   DB_HOST=10.1.2.3 ./vm-start.sh   # same thing
#
# What it does, in order: writes packages/app/.env from the settings, checks the
# database and Redis are reachable, applies migrations, builds, and brings up the
# pm2 topology in ecosystem.config.cjs. Exits once the cluster is serving —
# the processes stay running under the pm2 daemon.
#
# Options:
#   --seed          create the admin user and seed the dataset after starting
#   --no-build      reuse the existing build (fast restart after a config change)
#   --no-migrate    skip migrations
#   --config FILE   read settings from FILE instead of vm.env
#   Any setting from vm.env.example can be given as a flag: --db-host, --redis-port, ...
set -euo pipefail

# shellcheck source=vm-lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/vm-lib.sh"

SEED_DATA=0
SKIP_BUILD=0
SKIP_MIGRATE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --seed)       SEED_DATA=1; shift ;;
    --no-build)   SKIP_BUILD=1; shift ;;
    --no-migrate) SKIP_MIGRATE=1; shift ;;
    --config)     CONFIG_FILE="$2"; shift 2 ;;
    -h|--help)    sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    --*=*)        export "$(flag_to_var "${1%%=*}")=${1#*=}"; shift ;;
    --*)          [ $# -ge 2 ] || die "Missing value for $1"
                  export "$(flag_to_var "$1")=$2"; shift 2 ;;
    *)            die "Unexpected argument: $1" ;;
  esac
done

cd "$REPO_ROOT"
load_config
apply_defaults
require_config

APP_DIR="$REPO_ROOT/packages/app"
ENV_FILE="$APP_DIR/.env"

# ---------------------------------------------------------------------------
step "Connectivity"

if tcp_reachable "$DB_HOST" "$DB_PORT"; then
  ok "postgres $DB_HOST:$DB_PORT reachable"
else
  die "Cannot reach Postgres at $DB_HOST:$DB_PORT.
   Private IP: the VM needs to be on the same VPC and the instance needs a
   private services connection. Public IP: authorise this VM's address on the
   Cloud SQL instance, or run the Cloud SQL Auth Proxy and use 127.0.0.1."
fi

if tcp_reachable "$REDIS_HOST" "$REDIS_PORT"; then
  ok "redis $REDIS_HOST:$REDIS_PORT reachable"
else
  die "Cannot reach Redis at $REDIS_HOST:$REDIS_PORT.
   Memorystore is private-IP only — the VM must be on the authorised network."
fi

if have psql; then
  SERVER_VERSION="$(db_scalar 'show server_version;' || true)"
  if [ -z "$SERVER_VERSION" ]; then
    die "Reached $DB_HOST:$DB_PORT but could not authenticate as '$DB_USER' on '$DB_NAME'.
   Check DB_USER / DB_PASSWORD / DB_NAME, and that the database exists."
  fi
  ok "authenticated — postgres $SERVER_VERSION"
else
  warn "psql not installed; skipping the credential check"
fi

# ---------------------------------------------------------------------------
step "Writing $ENV_FILE"

# Reuse the secrets already on disk rather than minting new ones on every start:
# rotating them silently invalidates every logged-in admin session and every
# customer token the workload driver is holding.
existing_env_var() {
  [ -f "$ENV_FILE" ] || return 0
  grep -m1 "^$1=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true
}

: "${JWT_SECRET:=$(existing_env_var JWT_SECRET)}"
: "${COOKIE_SECRET:=$(existing_env_var COOKIE_SECRET)}"
: "${JWT_SECRET:=$(openssl rand -hex 32 2>/dev/null || node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("hex"))')}"
: "${COOKIE_SECRET:=$(openssl rand -hex 32 2>/dev/null || node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("hex"))')}"

RESOLVED_PUBLIC_HOST="$(detect_public_host)"
ORIGINS="http://localhost:$PORT,http://127.0.0.1:$PORT"
if [ "$RESOLVED_PUBLIC_HOST" != "localhost" ]; then
  ORIGINS="$ORIGINS,http://$RESOLVED_PUBLIC_HOST:$PORT,https://$RESOLVED_PUBLIC_HOST"
fi

DATABASE_URL_VALUE="$(database_url)"
REDIS_URL_VALUE="$(redis_url)"

cat > "$ENV_FILE" <<EOF
# Generated by vm-start.sh — edits here are overwritten on the next start.
# Change vm.env instead.

DATABASE_URL=$DATABASE_URL_VALUE
DB_SSL=$DB_SSL

REDIS_URL=$REDIS_URL_VALUE
REDIS_DB_ISOLATION=$REDIS_DB_ISOLATION

STORE_CORS=$ORIGINS
ADMIN_CORS=$ORIGINS
AUTH_CORS=$ORIGINS

JWT_SECRET=$JWT_SECRET
COOKIE_SECRET=$COOKIE_SECRET
EOF
chmod 600 "$ENV_FILE"

ok "database  $DB_USER@$DB_HOST:$DB_PORT/$DB_NAME (ssl=$DB_SSL)"
ok "redis     $REDIS_HOST:$REDIS_PORT (tls=${REDIS_TLS:-false}, auth=$([ -n "${REDIS_PASSWORD:-}" ] && echo yes || echo no))"
ok "cors      $ORIGINS"

# ---------------------------------------------------------------------------
# pm2's daemon inherits the limits of whatever shell first started it, so raise
# them here rather than hoping the login shell already had them.
ulimit -n 65535 2>/dev/null || true

step "Starting the cluster"

info "instances  ${MEDUSA_SERVER_INSTANCES:-auto} servers, ${MEDUSA_WORKER_INSTANCES:-auto} workers ($(nproc) cores)"
info "pool       $DB_CONNECTION_BUDGET connections shared across the processes"

if [ "$SKIP_MIGRATE" -eq 0 ]; then
  npm run db:setup
fi

if [ "$SKIP_BUILD" -eq 1 ]; then
  # Straight to the app's own task, bypassing turbo's build dependency.
  npm run --workspace @ecommerce-load/app run:app
else
  npm run run:app
fi

# ---------------------------------------------------------------------------
if [ "$SEED_DATA" -eq 1 ]; then
  step "Seeding"

  # Seeding runs against the live cluster on purpose: the workload dataset leans
  # on subscribers and the workflow engine, which only run on the pm2 workers.
  if have psql; then
    PRODUCTS="$(db_scalar "select count(*) from product where deleted_at is null;" || echo 0)"
    if [ "${PRODUCTS:-0}" -gt 10 ]; then
      warn "database already holds $PRODUCTS products — seeding again will duplicate the catalogue"
      warn "press Ctrl-C within 10s to stop"
      sleep 10
    fi
  fi

  info "admin user $ADMIN_EMAIL"
  (cd "$APP_DIR" && npx medusa user -e "$ADMIN_EMAIL" -p "$ADMIN_PASSWORD") \
    || warn "admin user already exists — continuing"

  npm run --workspace @ecommerce-load/app seed
  npm run --workspace @ecommerce-load/app seed:workload

  ok "dataset seeded"
fi

# ---------------------------------------------------------------------------
step "Up"

cat <<EOF

  api / admin   http://$RESOLVED_PUBLIC_HOST:$PORT/app
  health        curl -s http://localhost:$PORT/health

  status        npm run status:app
  logs          npm run logs:app
  reload        npm run restart:app
  stop          npm run stop:app

  verify        ./vm-check.sh
  load          ./vm-run-load.sh <duration_min> <anomaly_start_min> <anomaly_end_min>

EOF

if [ "$RESOLVED_PUBLIC_HOST" != "localhost" ]; then
  dim "The dashboard needs a firewall rule allowing tcp:$PORT to this VM."
fi
